name = "Kaul Theme"
license = "MIT"
licenselink = "https://github.com/mjkaul/website/blob/main/LICENSE"
description = "A minimal theme matching matthewkaul.com"
homepage = "https://github.com/mjkaul/website"
min_version = "0.91.0"

[author]
  name = "Matthew Kaul"
  homepage = "https://matthewkaul.com"
